services:
  test_tensorflow_28:
    build:
      dockerfile: .ci/nox_tests
      context: ../
    command: nox --sessions tests_tensorflow_28

  test_tensorflow_29:
    build:
      dockerfile: .ci/nox_tests
      context: ../
    command: nox --sessions tests_tensorflow_29

  tests_tensorflow_10:
    build:
      dockerfile: .ci/nox_tests
      context: ../
    command: nox --sessions tests_tensorflow_10
    volumes:
      - /tmp:/tmp