services:
  test_tensorflow_28:
    build:
      dockerfile: .ci/nox_tests
      context: ../
    command: nox --sessions tests_tensorflow_28
  test_latest_tensorflow_version:
    build:
      dockerfile: .ci/nox_tests
      context: ../
    command: nox --sessions tests_tensorflow_latest
    volumes:
      - /tmp:/tmp