# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

import pathlib

#package_dir = pathlib.Path(__file__).parent.parent / "gianlp"
#sys.path.insert(0, str(package_dir))
#print(package_dir)

sys.path.insert(0, os.path.abspath('..'))
print(os.path.abspath('..'))


# sys.path.append(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'gianlp'))


# -- Project information -----------------------------------------------------

project = 'GiaNLP'
copyright = '2022, Gianmarco Cafferata'
author = 'Gianmarco Cafferata'

# The full version, including alpha/beta/rc tags
release = '0.0.1'
version = '0.0.1'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.napoleon',
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    #'sphinx.ext.mathjax',
    #'sphinx.ext.viewcode',
    #'sphinx.ext.githubpages',
    'm2r2'
]

napoleon_google_docstring = False
autosummary_generate = True  # Turn on sphinx.ext.autosummary

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

autoclass_content = 'both'
autodoc_member_order = 'bysource'

html_css_files = [
    'styles.css',
]


html_context = {
    "display_github": True,
    "github_user": "jian01",
    "github_repo": "GiaNLP",
    "github_version": "main",
    "conf_py_path": "/docs/",
    "source_suffix": ".rst",
}