name: Documentation

on: push

jobs:
  update_templates:
    name: "Update Templates"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "💾  Github Repository Metadata"
        uses: varunsridharan/action-repository-meta@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "💫  Dynamic Template Render"
        uses: varunsridharan/action-dynamic-readme@main
        with:
          commit_message: 'Dynamic markdown update'
          committer_name: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com
          GLOBAL_TEMPLATE_REPOSITORY: jian01/gianlp
          files: |
            md_templates/README.md=README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  sphinx-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install nox
      - name: Build with latest sphinx version
        run: nox --sessions test_sphinx_build