name: Tests on latest tensorflow version

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 50
    steps:
    - uses: actions/checkout@v2
    - name: Run tests with tensorflow latest checked version
      run: docker-compose -f .ci/docker-compose.yml run tests_tensorflow_10
    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        files: /tmp/coverage.xml
        fail_ci_if_error: true
        verbose: true