name: Run tests on all versions

on: [pull_request, workflow_dispatch]

jobs:
  test_tensorflow_28:
    runs-on: ubuntu-latest
    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v2
      - name: Run tests with tensorflow 2.8.0
        run: docker-compose -f .ci/docker-compose.yml run test_tensorflow_28
  test_tensorflow_29:
    runs-on: ubuntu-latest
    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v2
      - name: Run tests with tensorflow 2.9.0
        run: docker-compose -f .ci/docker-compose.yml run test_tensorflow_29